/**
 * Country of Operator/Owner
 */
export const CountryOfOperator_Owner = [
  "USA",
  "United Kingdom",
  "Finland",
  "Denmark",
  "Multinational",
  "Israel",
  "Austria",
  "ESA",
  "Lithuania",
  "Norway",
  "Spain",
  "United Arab Emirates",
  "Kazakhstan",
  "Algeria",
  "Japan",
  "Brazil",
  "Russia",
  "South Korea",
  "Angola",
  "Canada",
  "Argentina",
  "USA/Argentina",
  "China",
  "Belgium",
  "Turkey",
  "Luxembourg",
  "Switzerland",
  "India",
  "France/Italy",
  "Singapore",
  "Azerbaijan",
  "Bangladesh",
  "Czech Republic",
  "Germany",
  "Belarus",
  "Netherlands",
  "Indonesia",
  "France",
  "Australia",
  "Bulgaria",
  "China/Brazil",
  "China/France",
  "Tunisia",
  "Taiwan",
  "Italy",
  "Mexico",
  "Ecuador",
  "Egypt",
  "USA/Canada/Japan",
  "USA/Japan/Brazil",
  "Ethiopia",
  "Colombia",
  "USA/Japan",
  "USA/Germany",
  "France/Italy/Belgium/Spain/Greece",
  "Greece",
  "Greece/United Kingdom",
  "United Kingdom/ESA",
  "Malaysia",
  "USA/India/Singapore/Taiwan",
  "ESA/Russia",
  "Thailand",
  "USA/France",
  "Japan/Singapore",
  "Jordan",
  "Iran",
  "Saudi Arabia",
  "Kuwait",
  "United Kingdom/Netherlands",
  "Laos",
  "Morocco/Germany",
  "South Africa",
  "India/France",
  "Vietnam",
  "Morocco",
  "USA/Canada",
  "Slovenia",
  "Sinapore",
  "Nigeria",
  "Sweden",
  "Pakistan",
  "Peru",
  "New Zealand",
  "Chile",
  "Ukraine",
  "Hungary",
  "India/Canada",
  "Monaco",
  "Nepal",
  "France/Belgium/Sweden",
  "Sudan",
  "Singapore/Taiwan",
  "USA/Poland",
  "Poland/UK",
  "Poland",
  "USA/United Kingdom/Italy",
  "Kenya",
  "Iraq",
  "Bolivia",
  "Estonia",
  "Turkmenistan/Monaco",
  "France/Israel",
  "Venezuela",
  "China/Italy",
];

export const CountryOfOperator_Owner_Colors = {
  USA: "#1E90FF",
  "United Kingdom": "#E74C3C",
  Finland: "#E74C3C",
  Denmark: "#E74C3C",
  Multinational: "#FFFFFF",
  Israel: "#F1C40F",
  Austria: "#E74C3C",
  ESA: "#FFFFFF",
  Lithuania: "#E74C3C",
  Norway: "#E74C3C",
  Spain: "#E74C3C",
  "United Arab Emirates": "#F1C40F",
  Kazakhstan: "#E67E22",
  Algeria: "#8B4513",
  Japan: "#9B59B6",
  Brazil: "#2ECC71",
  Russia: "#E67E22",
  "South Korea": "#9B59B6",
  Angola: "#8B4513",
  Canada: "#1E90FF",
  Argentina: "#2ECC71",
  "USA/Argentina": "#1E90FF",
  China: "#9B59B6",
  Belgium: "#E74C3C",
  Turkey: "#7F8C8D",
  Luxembourg: "#E74C3C",
  Switzerland: "#E74C3C",
  India: "#9B59B6",
  "France/Italy": "#E74C3C",
  Singapore: "#7F8C8D",
  Azerbaijan: "#7F8C8D",
  Bangladesh: "#9B59B6",
  "Czech Republic": "#E74C3C",
  Germany: "#E74C3C",
  Belarus: "#E67E22",
  Netherlands: "#E74C3C",
  Indonesia: "#9B59B6",
  France: "#E74C3C",
  Australia: "#1ABC9C",
  Bulgaria: "#E74C3C",
  "China/Brazil": "#9B59B6",
  "China/France": "#9B59B6",
  Tunisia: "#8B4513",
  Taiwan: "#9B59B6",
  Italy: "#E74C3C",
  Mexico: "#1E90FF",
  Ecuador: "#2ECC71",
  Egypt: "#8B4513",
  "USA/Canada/Japan": "#1E90FF",
  "USA/Japan/Brazil": "#1E90FF",
  Ethiopia: "#8B4513",
  Colombia: "#2ECC71",
  "USA/Japan": "#1E90FF",
  "USA/Germany": "#1E90FF",
  "France/Italy/Belgium/Spain/Greece": "#FFFFFF",
  Greece: "#E74C3C",
  "Greece/United Kingdom": "#E74C3C",
  "United Kingdom/ESA": "#FFFFFF",
  Malaysia: "#9B59B6",
  "USA/India/Singapore/Taiwan": "#1E90FF",
  "ESA/Russia": "#FFFFFF",
  Thailand: "#9B59B6",
  "USA/France": "#1E90FF",
  "Japan/Singapore": "#9B59B6",
  Jordan: "#F1C40F",
  Iran: "#F1C40F",
  "Saudi Arabia": "#F1C40F",
  Kuwait: "#F1C40F",
  "United Kingdom/Netherlands": "#E74C3C",
  Laos: "#9B59B6",
  "Morocco/Germany": "#8B4513",
  "South Africa": "#8B4513",
  "India/France": "#9B59B6",
  Vietnam: "#9B59B6",
  Morocco: "#8B4513",
  "USA/Canada": "#1E90FF",
  Slovenia: "#E74C3C",
  Sinapore: "#7F8C8D",
  Nigeria: "#8B4513",
  Sweden: "#E74C3C",
  Pakistan: "#9B59B6",
  Peru: "#2ECC71",
  "New Zealand": "#1ABC9C",
  Chile: "#2ECC71",
  Ukraine: "#E67E22",
  Hungary: "#E74C3C",
  "India/Canada": "#9B59B6",
  Monaco: "#E74C3C",
  Nepal: "#9B59B6",
  "France/Belgium/Sweden": "#E74C3C",
  Sudan: "#8B4513",
  "Singapore/Taiwan": "#7F8C8D",
  "USA/Poland": "#1E90FF",
  "Poland/UK": "#E74C3C",
  Poland: "#E74C3C",
  "USA/United Kingdom/Italy": "#1E90FF",
  Kenya: "#8B4513",
  Iraq: "#F1C40F",
  Bolivia: "#2ECC71",
  Estonia: "#E74C3C",
  "Turkmenistan/Monaco": "#E67E22",
  "France/Israel": "#E74C3C",
  Venezuela: "#2ECC71",
  "China/Italy": "#9B59B6",
};

/**
 * Country/Org of UN Registry
 */
export const Country_OrgOfUNRegistry = [
  "NR",
  "United Kingdom",
  "Finland",
  "Denmark",
  "NR (9/23)",
  "USA",
  "ESA",
  "France",
  "Lithuania",
  "Norway",
  "Spain",
  "Brazil",
  "Algeria",
  "Russia",
  "South Korea",
  "NR (12/22)",
  "Canada",
  "China",
  "NR (4/22)",
  "NR (1/22)",
  "Argentina",
  "Belgium",
  "Japan",
  "Luxembourg",
  "India",
  "Azerbaijan",
  "Germany",
  "Belarus",
  "Netherlands",
  "Indonesia",
  "Australia",
  "United KIngdom",
  "Turkey",
  "Italy",
  "United Arab Emirates",
  "NR (5/21)",
  "NR (12/20)",
  "South Africa",
  "Ethiopia",
  "Mexico",
  "NR (9/21)",
  "Colombia",
  "Inda",
  "Greece",
  "Kazakhstan",
  "Laos",
  "Czech Republic",
  "Malaysia",
  "EUMETSAT",
  "EUMETSAT/ESA",
  "Nigeria",
  "NR (9_22)",
  "Uruguay",
  "Sweden",
  "Pakistan",
  "New Zealand",
  "Peru",
  "Saudi Arabia",
  "Chile",
  "Thailand",
  "Egypt",
  "Iraq",
  "Bolivia",
  "NR (9/22)",
  "Austria",
  "Israel",
  "Venezuela",
  "China/Sri Lanka",
];

export const Country_OrgOfUNRegistry_Colors = {
  NR: "#cccccc",
  "United Kingdom": "#ff6699",
  Finland: "#ffccff",
  Denmark: "#ff99cc",
  "NR (9/23)": "#cccccc",
  USA: "#ff6666",
  ESA: "#6699ff",
  France: "#ff99cc",
  Lithuania: "#ffcc99",
  Norway: "#6699cc",
  Spain: "#cc99ff",
  Brazil: "#99ff99",
  Algeria: "#ffcc66",
  Russia: "#ff9966",
  "South Korea": "#99ffcc",
  "NR (12/22)": "#cccccc",
  Canada: "#66ccff",
  China: "#ff9966",
  "NR (4/22)": "#cccccc",
  "NR (1/22)": "#cccccc",
  Argentina: "#cc99cc",
  Belgium: "#ffccff",
  Japan: "#ffccff",
  Luxembourg: "#66ffcc",
  India: "#ffcc00",
  Azerbaijan: "#ff9966",
  Germany: "#ff99ff",
  Belarus: "#99ccff",
  Netherlands: "#99ffcc",
  Indonesia: "#cc99cc",
  Australia: "#cccc99",
  "United KIngdom": "#ff6699",
  Turkey: "#cc6666",
  Italy: "#66ffcc",
  "United Arab Emirates": "#99cccc",
  "NR (5/21)": "#cccccc",
  "NR (12/20)": "#cccccc",
  "South Africa": "#9966cc",
  Ethiopia: "#ff3366",
  Mexico: "#cc9966",
  "NR (9/21)": "#cccccc",
  Colombia: "#ff6666",
  Inda: "#ff9966",
  Greece: "#ff3366",
  Kazakhstan: "#ff9966",
  Laos: "#99ff99",
  "Czech Republic": "#99ccff",
  Malaysia: "#66ccff",
  EUMETSAT: "#6699ff",
  "EUMETSAT/ESA": "#6699ff",
  Nigeria: "#66cc99",
  "NR (9_22)": "#cccccc",
  Uruguay: "#ff9966",
  Sweden: "#ffccff",
  Pakistan: "#ff99cc",
  "New Zealand": "#66ccff",
  Peru: "#ff3366",
  "Saudi Arabia": "#cc6666",
  Chile: "#cc99ff",
  Thailand: "#ff6633",
  Egypt: "#ff9966",
  Iraq: "#ff3366",
  Bolivia: "#cc9966",
  "NR (9/22)": "#cccccc",
  Austria: "#ff9966",
  Israel: "#99ffcc",
  Venezuela: "#cc6666",
  "China/Sri Lanka": "#ffcc99",
};

export const Users = [
  "Commercial",
  "Civil",
  "Government",
  "Military",
  "Military/Commercial",
  "Government/Military",
  "Military/Government",
  "Government/Civil",
  "Military/Civil",
  "Commercial/Civil",
  "Civil/Commercial",
  "Government/Commercial",
  "Commercial/Government",
  "Government/Commercial/Military",
  "Civil/Government",
  "Civil/Military",
  "Commercial/Military",
];

export const Users_Colors = {
  Commercial: "#ffcc00",
  Civil: "#33ccff",
  Government: "#ff9966",
  Military: "#ff3300",
  "Military/Commercial": "#ff6633",
  "Government/Military": "#ff6600",
  "Military/Government": "#ff6600",
  "Government/Civil": "#6699ff",
  "Military/Civil": "#ff3366",
  "Commercial/Civil": "#66ccff",
  "Civil/Commercial": "#66ccff",
  "Government/Commercial": "#ff9900",
  "Commercial/Government": "#ff9900",
  "Government/Commercial/Military": "#cc6600",
  "Civil/Government": "#99ccff",
  "Civil/Military": "#ff6666",
  "Commercial/Military": "#ff9966",
};

export const Purpose = [
  "Earth Observation",
  "Technology Development",
  "Communications",
  "Earth Science",
  "Space Science",
  "Space Science/Technology Demonstration",
  "Communications/Technology Development",
  "Communications/Maritime Tracking",
  "Technology Demonstration",
  "Unknown",
  "Navigation/Global Positioning",
  "Earth Observation/Technology Development",
  "Earth Observation/Communications",
  "Earth/Space Observation",
  "Educational",
  "Earth Observation/Earth Science",
  "Platform",
  "Earth Observation/Space Science",
  "Earth Observation/Navigation",
  "Communications/Navigation",
  "Space Observation",
  "Surveillance",
  "Navigation/Regional Positioning",
  "Space Science/Technology Development",
  "Mission Extension Technology",
  "Earth Science/Earth Observation",
  "Earth Observation/Communications/Space Science",
  "Meteorological",
  "Technology Development/Educational",
  "Satellite Positioning",
];

export const Purpose_Colors = {
  "Earth Observation": "#33ccff",
  "Technology Development": "#66ff66",
  Communications: "#ffcc00",
  "Earth Science": "#99ff99",
  "Space Science": "#ff3399",
  "Space Science/Technology Demonstration": "#ff66cc",
  "Communications/Technology Development": "#ff9966",
  "Communications/Maritime Tracking": "#ffcc33",
  "Technology Demonstration": "#66ffcc",
  Unknown: "#cccccc",
  "Navigation/Global Positioning": "#ff6600",
  "Earth Observation/Technology Development": "#33ff99",
  "Earth Observation/Communications": "#ffcc99",
  "Earth/Space Observation": "#99ccff",
  Educational: "#ffff66",
  "Earth Observation/Earth Science": "#99ffcc",
  Platform: "#cccc66",
  "Earth Observation/Space Science": "#cc99ff",
  "Earth Observation/Navigation": "#ff9933",
  "Communications/Navigation": "#ff9966",
  "Space Observation": "#66ccff",
  Surveillance: "#ff3300",
  "Navigation/Regional Positioning": "#ff6600",
  "Space Science/Technology Development": "#ff6699",
  "Mission Extension Technology": "#33ff66",
  "Earth Science/Earth Observation": "#66ff99",
  "Earth Observation/Communications/Space Science": "#ffcc66",
  Meteorological: "#6699ff",
  "Technology Development/Educational": "#99ff66",
  "Satellite Positioning": "#ff9900",
};

export const TypesOfOrbit = [
  "Non-Polar Inclined",
  "Sun-Synchronous",
  "Equatorial",
  "Polar",
  "Elliptical",
  "Deep Highly Eccentric",
  "Molniya",
  "Retrograde",
  "Cislunar",
  "Sun-Synchronous Near Polar",
  "Unknown",
];
export const TypesOfOrbit_Colors = {
  Elliptical: "#ff3399",
  Polar: "#66ff66",
  "Sun-Synchronous": "#ff99cc",
  Molniya: "#cc33ff",
  Retrograde: "#ff3300",
  Cislunar: "#99ccff",
  "Deep Highly Eccentric": "#ff9966",
  "Sun-Synchronous Near Polar": "#66ffff",
  "Non-Polar Inclined": "#99ff99",
  Equatorial: "#ffff66",
  Unknown: "#dddddd",
};

export const ClassesOfOrbit = ["LEO", "GEO", "Elliptical", "MEO", "Unknown"];
export const ClassesOfOrbit_Colors = {
  LEO: "#ffcc00",
  MEO: "#33ccff",
  GEO: "#ff6600",
  Elliptical: "#ff3399",
  Unknown: "#dddddd",
};

export const TheFirstDateOfLaunch = Date.parse(`11/15/1974`);
export const TheLastDateOfLaunch = Date.parse(`04/27/2023`);
